Produce valid output for @include
```
@include foo
```
Currently produces
```
@include () {}
```
Which is not valid sass and produces the following error
```
Error: Mixin "foo" does not accept a content block.
```
This patch changes the output
```
@include foo();
```